# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/felipe/Documents/C-C++/SDL/livro

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/felipe/Documents/C-C++/SDL/livro

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/felipe/Documents/C-C++/SDL/livro/CMakeFiles /home/felipe/Documents/C-C++/SDL/livro/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/felipe/Documents/C-C++/SDL/livro/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rgbender

# Build rule for target.
rgbender: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rgbender
.PHONY : rgbender

# fast build rule for target.
rgbender/fast:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/build
.PHONY : rgbender/fast

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/build
.PHONY : engine/fast

src/BossBullet.o: src/BossBullet.cpp.o
.PHONY : src/BossBullet.o

# target to build an object file
src/BossBullet.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/BossBullet.cpp.o
.PHONY : src/BossBullet.cpp.o

src/BossBullet.i: src/BossBullet.cpp.i
.PHONY : src/BossBullet.i

# target to preprocess a source file
src/BossBullet.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/BossBullet.cpp.i
.PHONY : src/BossBullet.cpp.i

src/BossBullet.s: src/BossBullet.cpp.s
.PHONY : src/BossBullet.s

# target to generate assembly for a file
src/BossBullet.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/BossBullet.cpp.s
.PHONY : src/BossBullet.cpp.s

src/Bullet.o: src/Bullet.cpp.o
.PHONY : src/Bullet.o

# target to build an object file
src/Bullet.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/Bullet.cpp.o
.PHONY : src/Bullet.cpp.o

src/Bullet.i: src/Bullet.cpp.i
.PHONY : src/Bullet.i

# target to preprocess a source file
src/Bullet.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/Bullet.cpp.i
.PHONY : src/Bullet.cpp.i

src/Bullet.s: src/Bullet.cpp.s
.PHONY : src/Bullet.s

# target to generate assembly for a file
src/Bullet.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/Bullet.cpp.s
.PHONY : src/Bullet.cpp.s

src/ChairBullet.o: src/ChairBullet.cpp.o
.PHONY : src/ChairBullet.o

# target to build an object file
src/ChairBullet.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/ChairBullet.cpp.o
.PHONY : src/ChairBullet.cpp.o

src/ChairBullet.i: src/ChairBullet.cpp.i
.PHONY : src/ChairBullet.i

# target to preprocess a source file
src/ChairBullet.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/ChairBullet.cpp.i
.PHONY : src/ChairBullet.cpp.i

src/ChairBullet.s: src/ChairBullet.cpp.s
.PHONY : src/ChairBullet.s

# target to generate assembly for a file
src/ChairBullet.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/ChairBullet.cpp.s
.PHONY : src/ChairBullet.cpp.s

src/ChildBullet.o: src/ChildBullet.cpp.o
.PHONY : src/ChildBullet.o

# target to build an object file
src/ChildBullet.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/ChildBullet.cpp.o
.PHONY : src/ChildBullet.cpp.o

src/ChildBullet.i: src/ChildBullet.cpp.i
.PHONY : src/ChildBullet.i

# target to preprocess a source file
src/ChildBullet.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/ChildBullet.cpp.i
.PHONY : src/ChildBullet.cpp.i

src/ChildBullet.s: src/ChildBullet.cpp.s
.PHONY : src/ChildBullet.s

# target to generate assembly for a file
src/ChildBullet.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/ChildBullet.cpp.s
.PHONY : src/ChildBullet.cpp.s

src/Childmaiden.o: src/Childmaiden.cpp.o
.PHONY : src/Childmaiden.o

# target to build an object file
src/Childmaiden.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/Childmaiden.cpp.o
.PHONY : src/Childmaiden.cpp.o

src/Childmaiden.i: src/Childmaiden.cpp.i
.PHONY : src/Childmaiden.i

# target to preprocess a source file
src/Childmaiden.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/Childmaiden.cpp.i
.PHONY : src/Childmaiden.cpp.i

src/Childmaiden.s: src/Childmaiden.cpp.s
.PHONY : src/Childmaiden.s

# target to generate assembly for a file
src/Childmaiden.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/Childmaiden.cpp.s
.PHONY : src/Childmaiden.cpp.s

src/Enemy.o: src/Enemy.cpp.o
.PHONY : src/Enemy.o

# target to build an object file
src/Enemy.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/Enemy.cpp.o
.PHONY : src/Enemy.cpp.o

src/Enemy.i: src/Enemy.cpp.i
.PHONY : src/Enemy.i

# target to preprocess a source file
src/Enemy.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/Enemy.cpp.i
.PHONY : src/Enemy.cpp.i

src/Enemy.s: src/Enemy.cpp.s
.PHONY : src/Enemy.s

# target to generate assembly for a file
src/Enemy.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/Enemy.cpp.s
.PHONY : src/Enemy.cpp.s

src/GameOverState.o: src/GameOverState.cpp.o
.PHONY : src/GameOverState.o

# target to build an object file
src/GameOverState.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/GameOverState.cpp.o
.PHONY : src/GameOverState.cpp.o

src/GameOverState.i: src/GameOverState.cpp.i
.PHONY : src/GameOverState.i

# target to preprocess a source file
src/GameOverState.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/GameOverState.cpp.i
.PHONY : src/GameOverState.cpp.i

src/GameOverState.s: src/GameOverState.cpp.s
.PHONY : src/GameOverState.s

# target to generate assembly for a file
src/GameOverState.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/GameOverState.cpp.s
.PHONY : src/GameOverState.cpp.s

src/MainMenuState.o: src/MainMenuState.cpp.o
.PHONY : src/MainMenuState.o

# target to build an object file
src/MainMenuState.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/MainMenuState.cpp.o
.PHONY : src/MainMenuState.cpp.o

src/MainMenuState.i: src/MainMenuState.cpp.i
.PHONY : src/MainMenuState.i

# target to preprocess a source file
src/MainMenuState.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/MainMenuState.cpp.i
.PHONY : src/MainMenuState.cpp.i

src/MainMenuState.s: src/MainMenuState.cpp.s
.PHONY : src/MainMenuState.s

# target to generate assembly for a file
src/MainMenuState.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/MainMenuState.cpp.s
.PHONY : src/MainMenuState.cpp.s

src/MenuButton.o: src/MenuButton.cpp.o
.PHONY : src/MenuButton.o

# target to build an object file
src/MenuButton.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/MenuButton.cpp.o
.PHONY : src/MenuButton.cpp.o

src/MenuButton.i: src/MenuButton.cpp.i
.PHONY : src/MenuButton.i

# target to preprocess a source file
src/MenuButton.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/MenuButton.cpp.i
.PHONY : src/MenuButton.cpp.i

src/MenuButton.s: src/MenuButton.cpp.s
.PHONY : src/MenuButton.s

# target to generate assembly for a file
src/MenuButton.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/MenuButton.cpp.s
.PHONY : src/MenuButton.cpp.s

src/PauseState.o: src/PauseState.cpp.o
.PHONY : src/PauseState.o

# target to build an object file
src/PauseState.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/PauseState.cpp.o
.PHONY : src/PauseState.cpp.o

src/PauseState.i: src/PauseState.cpp.i
.PHONY : src/PauseState.i

# target to preprocess a source file
src/PauseState.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/PauseState.cpp.i
.PHONY : src/PauseState.cpp.i

src/PauseState.s: src/PauseState.cpp.s
.PHONY : src/PauseState.s

# target to generate assembly for a file
src/PauseState.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/PauseState.cpp.s
.PHONY : src/PauseState.cpp.s

src/PlayState.o: src/PlayState.cpp.o
.PHONY : src/PlayState.o

# target to build an object file
src/PlayState.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/PlayState.cpp.o
.PHONY : src/PlayState.cpp.o

src/PlayState.i: src/PlayState.cpp.i
.PHONY : src/PlayState.i

# target to preprocess a source file
src/PlayState.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/PlayState.cpp.i
.PHONY : src/PlayState.cpp.i

src/PlayState.s: src/PlayState.cpp.s
.PHONY : src/PlayState.s

# target to generate assembly for a file
src/PlayState.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/PlayState.cpp.s
.PHONY : src/PlayState.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/ShieldSkill.o: src/ShieldSkill.cpp.o
.PHONY : src/ShieldSkill.o

# target to build an object file
src/ShieldSkill.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/ShieldSkill.cpp.o
.PHONY : src/ShieldSkill.cpp.o

src/ShieldSkill.i: src/ShieldSkill.cpp.i
.PHONY : src/ShieldSkill.i

# target to preprocess a source file
src/ShieldSkill.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/ShieldSkill.cpp.i
.PHONY : src/ShieldSkill.cpp.i

src/ShieldSkill.s: src/ShieldSkill.cpp.s
.PHONY : src/ShieldSkill.s

# target to generate assembly for a file
src/ShieldSkill.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/ShieldSkill.cpp.s
.PHONY : src/ShieldSkill.cpp.s

src/SkillManager.o: src/SkillManager.cpp.o
.PHONY : src/SkillManager.o

# target to build an object file
src/SkillManager.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/SkillManager.cpp.o
.PHONY : src/SkillManager.cpp.o

src/SkillManager.i: src/SkillManager.cpp.i
.PHONY : src/SkillManager.i

# target to preprocess a source file
src/SkillManager.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/SkillManager.cpp.i
.PHONY : src/SkillManager.cpp.i

src/SkillManager.s: src/SkillManager.cpp.s
.PHONY : src/SkillManager.s

# target to generate assembly for a file
src/SkillManager.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/SkillManager.cpp.s
.PHONY : src/SkillManager.cpp.s

src/WinGameState.o: src/WinGameState.cpp.o
.PHONY : src/WinGameState.o

# target to build an object file
src/WinGameState.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/WinGameState.cpp.o
.PHONY : src/WinGameState.cpp.o

src/WinGameState.i: src/WinGameState.cpp.i
.PHONY : src/WinGameState.i

# target to preprocess a source file
src/WinGameState.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/WinGameState.cpp.i
.PHONY : src/WinGameState.cpp.i

src/WinGameState.s: src/WinGameState.cpp.s
.PHONY : src/WinGameState.s

# target to generate assembly for a file
src/WinGameState.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/WinGameState.cpp.s
.PHONY : src/WinGameState.cpp.s

src/XuxaBoss.o: src/XuxaBoss.cpp.o
.PHONY : src/XuxaBoss.o

# target to build an object file
src/XuxaBoss.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/XuxaBoss.cpp.o
.PHONY : src/XuxaBoss.cpp.o

src/XuxaBoss.i: src/XuxaBoss.cpp.i
.PHONY : src/XuxaBoss.i

# target to preprocess a source file
src/XuxaBoss.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/XuxaBoss.cpp.i
.PHONY : src/XuxaBoss.cpp.i

src/XuxaBoss.s: src/XuxaBoss.cpp.s
.PHONY : src/XuxaBoss.s

# target to generate assembly for a file
src/XuxaBoss.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/XuxaBoss.cpp.s
.PHONY : src/XuxaBoss.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/rgbender.dir/build.make CMakeFiles/rgbender.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rgbender"
	@echo "... engine"
	@echo "... src/BossBullet.o"
	@echo "... src/BossBullet.i"
	@echo "... src/BossBullet.s"
	@echo "... src/Bullet.o"
	@echo "... src/Bullet.i"
	@echo "... src/Bullet.s"
	@echo "... src/ChairBullet.o"
	@echo "... src/ChairBullet.i"
	@echo "... src/ChairBullet.s"
	@echo "... src/ChildBullet.o"
	@echo "... src/ChildBullet.i"
	@echo "... src/ChildBullet.s"
	@echo "... src/Childmaiden.o"
	@echo "... src/Childmaiden.i"
	@echo "... src/Childmaiden.s"
	@echo "... src/Enemy.o"
	@echo "... src/Enemy.i"
	@echo "... src/Enemy.s"
	@echo "... src/GameOverState.o"
	@echo "... src/GameOverState.i"
	@echo "... src/GameOverState.s"
	@echo "... src/MainMenuState.o"
	@echo "... src/MainMenuState.i"
	@echo "... src/MainMenuState.s"
	@echo "... src/MenuButton.o"
	@echo "... src/MenuButton.i"
	@echo "... src/MenuButton.s"
	@echo "... src/PauseState.o"
	@echo "... src/PauseState.i"
	@echo "... src/PauseState.s"
	@echo "... src/PlayState.o"
	@echo "... src/PlayState.i"
	@echo "... src/PlayState.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/ShieldSkill.o"
	@echo "... src/ShieldSkill.i"
	@echo "... src/ShieldSkill.s"
	@echo "... src/SkillManager.o"
	@echo "... src/SkillManager.i"
	@echo "... src/SkillManager.s"
	@echo "... src/WinGameState.o"
	@echo "... src/WinGameState.i"
	@echo "... src/WinGameState.s"
	@echo "... src/XuxaBoss.o"
	@echo "... src/XuxaBoss.i"
	@echo "... src/XuxaBoss.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

